version: '3.3'
services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: bonbonb/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    image: bonbonb/frontend:latest
    restart: always
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    container_name: nginx
    image: nginx:1.21.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/nginx/html/staticfile/
      - media_value:/usr/share/nginx/html/mediafile/
    depends_on:
      - backend

volumes:
  data_value:
  static_value:
  media_value:

